### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by jayvdb** [jadelord/awkupy#1]
https://pypi.org/project/awkupy/ is 404 ;-(

**Comment by ashwinvis** [comment]
Yes indeed, I never got around to develop this further although it was a nice implementation. For the time being you can install the release from github:

```sh
pip install 'https://github.com/ashwinvis/awkupy/archive/0.0.2a0.tar.gz'
```

See how it works and if you really like it, I can try to make a release.

**Comment by ashwinvis** [comment]
I have also updated the examples and readme for a quick reference

**Comment by ashwinvis** [comment]
It is now released on beta: https://pypi.org/project/awkupy/ and much better than before.
